#ifndef __HWINTERFACES__
#define __HWINTERFACES__

#define GREEN_LED_PIN 12
#define RED_LED_PIN 13
#define OPEN_BUTTON_PIN 4
#define CLOSE_BUTTON_PIN 5
#define TEMP_SENSOR_PIN A0
#define USER_DETECTOR_PIN 2
#define SONAR_TRIG 6
#define SONAR_ECHO 7
#define SERVO_MOTOR_PIN 8

#endif